name: poafixmodule
publish_to: 'none'
environment:
  sdk: '^3.8.0'

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.development
    - .env.production
    - assets/poafix_logo.jpg
    - assets/icons/logo.png
    - assets/animations/loading.json
    - assets/animations/profile.json
    - assets/animations/empty_jobs.json
    - assets/illustrations/login_animation.json
    - assets/images/
    - assets/icons/
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.2.1
  google_fonts: ^6.2.0
  lottie: ^2.7.0
  sqflite: ^2.3.2
  path: ^1.9.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  flutter_rating_bar: ^4.0.1
  flutter_image_compress: ^2.1.0
  web_socket_channel: ^2.4.0
  logger: ^2.0.2
  socket_io_client: ^2.0.3
  dio: ^5.4.3
  flutter_secure_storage: ^9.0.0
  firebase_auth: ^4.19.2
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  timeago: ^3.6.0
  table_calendar: ^3.0.9
  agora_rtc_engine: ^6.2.6
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.5
  device_info_plus: ^10.1.2
  jwt_decoder: ^2.0.1
  flutter_local_notifications: ^19.4.0
  mongo_dart: ^0.10.5
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  flutter_ringtone_player: ^4.0.0+4
  vibration: ^3.1.3
  file_picker: ^8.0.7
  flutter_spinkit: ^5.2.2
  open_file: ^3.5.4
  font_awesome_flutter: ^10.9.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.0
  animations: ^2.0.11
  grouped_list: ^6.0.0
  provider: ^6.1.5
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  image: ^4.3.0
  shimmer: ^3.0.0
  webview_flutter: ^4.13.0
  flutter_dotenv: ^6.0.0
  flutter_animate: ^4.5.2


dev_dependencies:
  rive: ^0.12.4
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/poafix_logo.jpg"

